### ISSUE TITLE
No method to create an aab file public link automatically, as well as sending email for aab links

### ISSUE THREAD

**Issue by LiuCrane** [bitrise-steplib/steps-deploy-to-bitrise-io#141]
### Troubleshooting

- [ Yes] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? All versions
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Bitrise info

- Build URL: _Please share the build URL with us._
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES / NO_
- Log: 

<details>
  <pre>
 
  </pre>
</details>

### Steps to reproduce
I have checked the source code of the project, I noticed that unlike the DeployAPK function, the DeployAAB function does not requires parameters for enabling notifyEmails and publicLink, please can you fix it and keep behaviors of all outputs same based on step configurations.

**Comment by BirmacherAkos** [comment]
Hey @LiuCrane 👋   
thanks for the issue report.

Could you help me better understand your use case?
- Why would you need a public link for an  AAB?
- Why would you need an e-mail with the public link for an AAB?

----

**How does the step work now ( why there is no public link & e-mail for AAB ):**
The Deploy to Bitrise.io step generates a public link for build artifacts that you can install on a device. The step generates a link for APKs and IPAs, but it skips the generation for artifacts that can't be installed on a device directly.

Thus the step doesn't generate public link & e-mail for AABs as they are for Google Play deployment and not for device testing.

You can export **Universal APK** from the **AAB** with the **[Export Universal APK step](https://www.bitrise.io/integrations/steps/bitrise-step-export-universal-apk)** and the Deploy to Bitrise.io step will generate a public link & e-mail for the universal APK, just like for any other APKs.
_More: https://devcenter.bitrise.io/builds/build-artifacts-online/_

Even if the step doesn't generate a public link and e-mail for an artifact ( e.g: AAB ), the artifact is still available for download on the [APPS & Artifacts tab](https://devcenter.bitrise.io/builds/build-artifacts-online/).

**Comment by DJDarkByte** [comment]
I noticed the same "issue" as well, and while I can't speak for the use case of @LiuCrane I can give you mine.

Most of our apps get uploaded to the Play Store by our Bitrise workflow, but new apps that don't have a release in the Play Store yet can't be uploaded. For this situation we report back the public install url to a different department so they can download the APK and do the manual upload/release. After switching to AAB this doesn't work anymore, since there's no url to report back.

We don't really care about distributing the url for installation and don't use the e-mail functionality. The public install url is just the easiest way to get the files to the correct department, with the smallest probability of mistakes made by that department.

I do understand the logic about a public install url not really making sense for a file type that's not actually installable, but an alternative generated env var that contains a direct download link instead of the public install url would be fine as well in our case.

**Comment by BirmacherAkos** [comment]
Thanks  @DJDarkByte, your answer helped me better understand the problem.

I've added your insight to Productboard where we collect the requests.
We already have a feature request for providing fixed URLs for every exported artifact on the APPS & ARTIFACTS tab. I think your use case is related to that.
AFAIK  we'd need to do change in the backend as well, which makes it more difficult than an easy step update. 

But until we have the fixed URL for artifacts I think you can use one of these steps to deploy and generate URL for an ABB as a workaround:
- [Amazon S3 uploader](https://www.bitrise.io/integrations/steps/amazon-s3-uploader)
- [Firebase App Distribution](https://www.bitrise.io/integrations/steps/firebase-app-distribution)

**Comment by DJDarkByte** [comment]
Thanks for the response @BirmacherAkos .

The fixed URLs would indeed be a solution to the problem and completely fine for our use case. I'll be on the lookout for when that feature is implemented and use an alternative solution until then 🙂
