### ISSUE TITLE
wildcard for file type

### ISSUE THREAD

**Issue by kibotu** [bitrise-steplib/steps-deploy-to-bitrise-io#72]
hi,

i'd like to archive only a specific file type, e.g.: *.nupkg 

any ideas how i can achieve this?

best regards
Jan

**Comment by bitce** [comment]
Hi @kibotu 

You could achieve this by simply not generating any other artifacts. Is there something else to it that I'm not seeing? Let me know!

**Comment by bitce** [comment]
Oh I see, sorry I was interpreting this as more of a general question. 

Could you send us a build URL to see if there was something we could recommend to make your life easier in this extend?

Though generally, I would recommend checking our [feature request board](https://discuss.bitrise.io/c/feature-request) in similar cases, to see if someone has requested a similar feature already or to create a new one :) Because unfortunately the step does not allow to exclude archived files.

**Comment by kibotu** [comment]
i ended up adding a remove everything but the nugets script build step thanks though

**Comment by bitce** [comment]
Glad to hear that, way to go! :)
